Repository softeerbootcamp4th/Team6-AwesomeOrange-BE, pull requests merged in 2024-08, with the labels that each got.

#24 [feat] 선착순 이벤트 구현방안 1: Redis Lock 기반 (#23)
  build.gradle
  src/main/java/hyundai/softeer/orange/common/ErrorCode.java
  src/main/java/hyundai/softeer/orange/common/GlobalExceptionHandler.java
  src/main/java/hyundai/softeer/orange/config/WebConfig.java
  src/main/java/hyundai/softeer/orange/event/fcfs/ResponseFcfsWinnerDto.java
  src/main/java/hyundai/softeer/orange/event/fcfs/config/RedissonConfig.java
  src/main/java/hyundai/softeer/orange/event/fcfs/controller/FcfsController.java
  src/main/java/hyundai/softeer/orange/event/fcfs/entity/FcfsEvent.java
  src/main/java/hyundai/softeer/orange/event/fcfs/entity/FcfsEventWinningInfo.java
  src/main/java/hyundai/softeer/orange/event/fcfs/exception/FcfsEventException.java
  src/main/java/hyundai/softeer/orange/event/fcfs/repository/FcfsEventRepository.java
  src/main/java/hyundai/softeer/orange/event/fcfs/repository/FcfsEventWinningInfoRepository.java
  src/main/java/hyundai/softeer/orange/event/fcfs/scheduler/FcfsScheduler.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsManageService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisLockFcfsService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/util/FcfsUtil.java
  src/test/java/hyundai/softeer/orange/comment/CommentControllerTest.java
  src/test/java/hyundai/softeer/orange/event/fcfs/FcfsControllerTest.java
  src/test/java/hyundai/softeer/orange/event/fcfs/FcfsManageServiceUnitTest.java
  src/test/java/hyundai/softeer/orange/event/fcfs/RedisLockFcfsServiceLoadTest.java
Labels: feat

#25 [feat] 어드민 이벤트 생성 기능 구현(#21)
  src/main/java/hyundai/softeer/orange/admin/component/AdminArgumentResolver.java
  src/main/java/hyundai/softeer/orange/admin/controller/AdminController.java
  src/main/java/hyundai/softeer/orange/admin/dto/AdminSignInRequest.java
  src/main/java/hyundai/softeer/orange/admin/dto/AdminSignupRequest.java
  src/main/java/hyundai/softeer/orange/admin/entity/Admin.java
  src/main/java/hyundai/softeer/orange/admin/repository/AdminRepository.java
  src/main/java/hyundai/softeer/orange/admin/service/AdminAuthService.java
  src/main/java/hyundai/softeer/orange/comment/entity/Comment.java
  src/main/java/hyundai/softeer/orange/common/ErrorCode.java
  src/main/java/hyundai/softeer/orange/common/GlobalExceptionHandler.java
  src/main/java/hyundai/softeer/orange/common/util/DateUtil.java
  src/main/java/hyundai/softeer/orange/config/AppConfig.java
  src/main/java/hyundai/softeer/orange/config/WebConfig.java
  src/main/java/hyundai/softeer/orange/core/auth/Auth.java
  src/main/java/hyundai/softeer/orange/core/auth/AuthException.java
  src/main/java/hyundai/softeer/orange/core/auth/AuthInterceptor.java
  src/main/java/hyundai/softeer/orange/core/auth/AuthNameUtil.java
  src/main/java/hyundai/softeer/orange/core/auth/AuthRole.java
  src/main/java/hyundai/softeer/orange/core/jwt/JWTConst.java
  src/main/java/hyundai/softeer/orange/core/jwt/JWTManager.java
  src/main/java/hyundai/softeer/orange/event/common/EventConst.java
  src/main/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/EventFieldMapperMatcher.java
  src/main/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/DrawEventFieldMapper.java
  src/main/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/EventFieldMapper.java
  src/main/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/FcfsEventFieldMapper.java
  src/main/java/hyundai/softeer/orange/event/common/controller/EventController.java
  src/main/java/hyundai/softeer/orange/event/common/entity/EventMetadata.java
  src/main/java/hyundai/softeer/orange/event/common/enums/EventType.java
  src/main/java/hyundai/softeer/orange/event/common/exception/EventException.java
  src/main/java/hyundai/softeer/orange/event/common/repository/EventFrameRepository.java
  src/main/java/hyundai/softeer/orange/event/common/service/EventService.java
  src/main/java/hyundai/softeer/orange/event/component/EventKeyGenerator.java
  src/main/java/hyundai/softeer/orange/event/draw/entity/DrawEvent.java
  src/main/java/hyundai/softeer/orange/event/draw/entity/DrawEventMetadata.java
  src/main/java/hyundai/softeer/orange/event/draw/entity/DrawEventScorePolicy.java
  src/main/java/hyundai/softeer/orange/event/draw/enums/DrawEventAction.java
  src/main/java/hyundai/softeer/orange/event/dto/EventDto.java
  src/main/java/hyundai/softeer/orange/event/dto/EventFrameCreateRequest.java
  src/main/java/hyundai/softeer/orange/event/dto/draw/DrawEventDto.java
  src/main/java/hyundai/softeer/orange/event/dto/draw/DrawEventMetadataDto.java
  src/main/java/hyundai/softeer/orange/event/dto/draw/DrawEventScorePolicyDto.java
  src/main/java/hyundai/softeer/orange/event/dto/fcfs/FcfsEventDto.java
  src/main/java/hyundai/softeer/orange/event/dto/group/EventCreateGroup.java
  src/main/java/hyundai/softeer/orange/event/dto/group/EventEditGroup.java
  src/main/java/hyundai/softeer/orange/event/fcfs/entity/FcfsEvent.java
  src/test/java/hyundai/softeer/orange/core/auth/AuthNameUtilTest.java
  src/test/java/hyundai/softeer/orange/core/jwt/JWTManagerTest.java
  src/test/java/hyundai/softeer/orange/core/jwt/JwtTest.java
  src/test/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/EventFieldMapperMatcherTest.java
  src/test/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/DrawEventFieldMapperTest.java
  src/test/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/FcfsEventFieldMapperTest.java
  src/test/java/hyundai/softeer/orange/event/common/service/EventServiceTest.java
  src/test/java/hyundai/softeer/orange/event/component/EventKeyGeneratorTest.java
Labels: feat

#27 [feat] 단축 URL 구현 (#26)
  src/main/java/hyundai/softeer/orange/common/ErrorCode.java
  src/main/java/hyundai/softeer/orange/common/GlobalExceptionHandler.java
  src/main/java/hyundai/softeer/orange/common/util/ConstantUtil.java
  src/main/java/hyundai/softeer/orange/config/WebConfig.java
  src/main/java/hyundai/softeer/orange/event/fcfs/dto/ResponseFcfsWinnerDto.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsManageService.java
  src/main/java/hyundai/softeer/orange/event/url/controller/UrlController.java
  src/main/java/hyundai/softeer/orange/event/url/dto/ResponseUrlDto.java
  src/main/java/hyundai/softeer/orange/event/url/entity/Url.java
  src/main/java/hyundai/softeer/orange/event/url/exception/UrlException.java
  src/main/java/hyundai/softeer/orange/event/url/repository/UrlRepository.java
  src/main/java/hyundai/softeer/orange/event/url/service/UrlService.java
  src/main/java/hyundai/softeer/orange/event/url/util/UrlTypeValidation.java
  src/main/java/hyundai/softeer/orange/eventuser/repository/EventUserRepository.java
  src/test/java/hyundai/softeer/orange/event/fcfs/FcfsManageServiceUnitTest.java
  src/test/java/hyundai/softeer/orange/event/url/UrlControllerTest.java
  src/test/java/hyundai/softeer/orange/event/url/UrlServiceTest.java
Labels: feat

#31 [feat] 어드민 이벤트 수정 기능 구현(#28)
  build.gradle
  src/main/java/hyundai/softeer/orange/common/ErrorCode.java
  src/main/java/hyundai/softeer/orange/common/GlobalExceptionHandler.java
  src/main/java/hyundai/softeer/orange/config/AppConfig.java
  src/main/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/DrawEventFieldMapper.java
  src/main/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/EventFieldMapper.java
  src/main/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/FcfsEventFieldMapper.java
  src/main/java/hyundai/softeer/orange/event/common/controller/EventController.java
  src/main/java/hyundai/softeer/orange/event/common/entity/EventMetadata.java
  src/main/java/hyundai/softeer/orange/event/common/repository/EventMetadataRepository.java
  src/main/java/hyundai/softeer/orange/event/common/service/EventService.java
  src/main/java/hyundai/softeer/orange/event/component/EventKeyGenerator.java
  src/main/java/hyundai/softeer/orange/event/draw/entity/DrawEvent.java
  src/main/java/hyundai/softeer/orange/event/draw/entity/DrawEventMetadata.java
  src/main/java/hyundai/softeer/orange/event/draw/entity/DrawEventScorePolicy.java
  src/main/java/hyundai/softeer/orange/event/draw/repository/DrawEventRepository.java
  src/main/java/hyundai/softeer/orange/event/dto/EventDto.java
  src/main/java/hyundai/softeer/orange/event/dto/draw/DrawEventDto.java
  src/main/java/hyundai/softeer/orange/event/dto/draw/DrawEventMetadataDto.java
  src/main/java/hyundai/softeer/orange/event/dto/draw/DrawEventScorePolicyDto.java
  src/main/java/hyundai/softeer/orange/event/dto/fcfs/FcfsEventDto.java
  src/main/java/hyundai/softeer/orange/event/fcfs/entity/FcfsEvent.java
  src/test/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/EventFieldMapperMatcherTest.java
  src/test/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/DrawEventFieldMapperTest.java
  src/test/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/FcfsEventFieldMapperTest.java
  src/test/java/hyundai/softeer/orange/event/common/service/EventServiceTest.java
Labels: feat

#34 [feat] 선착순 이벤트 잔여 구현방안: Redis SortedSet + synchronized, DB Entity 기반 (#33)
  src/main/java/hyundai/softeer/orange/comment/controller/CommentController.java
  src/main/java/hyundai/softeer/orange/event/fcfs/controller/FcfsController.java
  src/main/java/hyundai/softeer/orange/event/fcfs/dto/ResponseFcfsResultDto.java
  src/main/java/hyundai/softeer/orange/event/fcfs/entity/FcfsEvent.java
  src/main/java/hyundai/softeer/orange/event/fcfs/repository/FcfsEventRepository.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/DbFcfsService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsAnswerService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsManageService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisLuaFcfsService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisSetFcfsService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/util/FcfsUtil.java
  src/main/java/hyundai/softeer/orange/event/url/controller/UrlController.java
  src/main/java/hyundai/softeer/orange/eventuser/controller/EventUserController.java
  src/main/java/hyundai/softeer/orange/eventuser/repository/EventUserRepository.java
  src/test/java/hyundai/softeer/orange/event/fcfs/FcfsControllerTest.java
  src/test/java/hyundai/softeer/orange/event/fcfs/FcfsManageServiceTest.java
  src/test/java/hyundai/softeer/orange/event/fcfs/FcfsManageServiceUnitTest.java
  src/test/java/hyundai/softeer/orange/event/fcfs/load/DbFcfsServiceLoadTest.java
  src/test/java/hyundai/softeer/orange/event/fcfs/load/RedisLockFcfsServiceLoadTest.java
  src/test/java/hyundai/softeer/orange/event/fcfs/load/RedisLuaFcfsServiceLoadTest.java
  src/test/java/hyundai/softeer/orange/event/fcfs/load/RedisSetFcfsServiceLoadTest.java
Labels: feat

#36 [feat] 관리자 이벤트 조회 기능 구현 (#32)
  src/main/java/hyundai/softeer/orange/config/AppConfig.java
  src/main/java/hyundai/softeer/orange/event/common/EventConst.java
  src/main/java/hyundai/softeer/orange/event/common/component/query/EventSearchQueryParser.java
  src/main/java/hyundai/softeer/orange/event/common/controller/EventController.java
  src/main/java/hyundai/softeer/orange/event/common/entity/EventFrame.java
  src/main/java/hyundai/softeer/orange/event/common/repository/EventMetadataRepository.java
  src/main/java/hyundai/softeer/orange/event/common/repository/EventSpecification.java
  src/main/java/hyundai/softeer/orange/event/common/service/EventService.java
  src/main/java/hyundai/softeer/orange/event/dto/BriefEventDto.java
  src/main/java/hyundai/softeer/orange/event/dto/EventDto.java
  src/main/java/hyundai/softeer/orange/event/dto/draw/DrawEventDto.java
  src/main/java/hyundai/softeer/orange/event/dto/draw/DrawEventMetadataDto.java
  src/main/java/hyundai/softeer/orange/event/dto/draw/DrawEventScorePolicyDto.java
  src/main/java/hyundai/softeer/orange/event/dto/fcfs/FcfsEventDto.java
  src/test/java/hyundai/softeer/orange/event/common/component/query/EventSearchQueryParserTest.java
  src/test/java/hyundai/softeer/orange/event/common/repository/EventSpecificationTest.java
  src/test/java/hyundai/softeer/orange/event/common/service/EventServiceSearchEventsTest.java
  src/test/java/hyundai/softeer/orange/event/common/service/EventServiceTest.java
Labels: feat

#39 [feat] 관리자 이벤트 댓글 조회 & 삭제 (#37)
  src/main/java/hyundai/softeer/orange/admin/controller/AdminCommentController.java
  src/main/java/hyundai/softeer/orange/comment/dto/DeleteCommentsDto.java
  src/main/java/hyundai/softeer/orange/comment/repository/CommentRepository.java
  src/main/java/hyundai/softeer/orange/comment/service/CommentService.java
  src/main/java/hyundai/softeer/orange/common/GlobalExceptionHandler.java
  src/main/java/hyundai/softeer/orange/event/common/controller/EventController.java
  src/main/java/hyundai/softeer/orange/event/common/repository/EventSpecification.java
  src/main/java/hyundai/softeer/orange/event/common/service/EventService.java
  src/main/java/hyundai/softeer/orange/event/draw/entity/DrawEvent.java
  src/main/java/hyundai/softeer/orange/event/dto/BriefEventDto.java
  src/main/java/hyundai/softeer/orange/event/dto/EventSearchHintDto.java
  src/main/java/hyundai/softeer/orange/eventuser/entity/EventUser.java
  src/test/java/hyundai/softeer/orange/event/common/repository/EventSpecificationTest.java
  src/test/java/hyundai/softeer/orange/event/common/service/EventServiceSearchEventsTest.java
  src/test/java/hyundai/softeer/orange/event/common/service/EventServiceSearchHintsTest.java
Labels: feat

#42 [fix] 선착순 이벤트 코드 수정 (#41)
  src/main/java/hyundai/softeer/orange/event/fcfs/repository/FcfsEventWinningInfoRepository.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/DbFcfsService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisLockFcfsService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisLuaFcfsService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisSetFcfsService.java
  src/test/java/hyundai/softeer/orange/event/fcfs/load/DbFcfsServiceLoadTest.java
Labels: fix

#43 [feat] 추첨 로직 구현(#40)
  infra/dev/db/docker-compose.yml
  src/main/java/hyundai/softeer/orange/admin/entity/Admin.java
  src/main/java/hyundai/softeer/orange/comment/dto/WriteCommentCountDto.java
  src/main/java/hyundai/softeer/orange/comment/repository/CommentRepository.java
  src/main/java/hyundai/softeer/orange/common/ErrorCode.java
  src/main/java/hyundai/softeer/orange/common/GlobalExceptionHandler.java
  src/main/java/hyundai/softeer/orange/event/draw/DrawEventConfig.java
  src/main/java/hyundai/softeer/orange/event/draw/component/picker/AccSumBasedWinnerPicker.java
  src/main/java/hyundai/softeer/orange/event/draw/component/picker/PickTarget.java
  src/main/java/hyundai/softeer/orange/event/draw/component/picker/WinnerPicker.java
  src/main/java/hyundai/softeer/orange/event/draw/component/score/ScoreCalculator.java
  src/main/java/hyundai/softeer/orange/event/draw/component/score/actionHandler/ActionHandler.java
  src/main/java/hyundai/softeer/orange/event/draw/component/score/actionHandler/ParticipateEventActionHandler.java
  src/main/java/hyundai/softeer/orange/event/draw/component/score/actionHandler/WriteCommentActionHandler.java
  src/main/java/hyundai/softeer/orange/event/draw/dto/DrawEventWinningInfoBulkInsertDto.java
  src/main/java/hyundai/softeer/orange/event/draw/dto/EventParticipateCountDto.java
  src/main/java/hyundai/softeer/orange/event/draw/enums/DrawEventAction.java
  src/main/java/hyundai/softeer/orange/event/draw/exception/DrawEventException.java
  src/main/java/hyundai/softeer/orange/event/draw/repository/CustomDrawEventWinningInfoRepository.java
  src/main/java/hyundai/softeer/orange/event/draw/repository/CustomDrawEventWinningInfoRepositoryImpl.java
  src/main/java/hyundai/softeer/orange/event/draw/repository/DrawEventRepository.java
  src/main/java/hyundai/softeer/orange/event/draw/repository/DrawEventWinningInfoRepository.java
  src/main/java/hyundai/softeer/orange/event/draw/repository/EventParticipationInfoRepository.java
  src/main/java/hyundai/softeer/orange/event/draw/service/DrawEventService.java
  src/main/java/hyundai/softeer/orange/eventuser/dto/EventUserScoreDto.java
  src/main/java/hyundai/softeer/orange/eventuser/repository/CustomEventUserRepository.java
  src/main/java/hyundai/softeer/orange/eventuser/repository/CustomEventUserRepositoryImpl.java
  src/main/java/hyundai/softeer/orange/eventuser/repository/EventUserRepository.java
  src/test/java/hyundai/softeer/orange/comment/repository/CommentRepositoryTest.java
  src/test/java/hyundai/softeer/orange/event/draw/component/picker/AccSumBasedWinnerPickerTest.java
  src/test/java/hyundai/softeer/orange/event/draw/component/score/ScoreCalculatorTest.java
  src/test/java/hyundai/softeer/orange/event/draw/component/score/actionHandler/ParticipateEventActionHandlerTest.java
  src/test/java/hyundai/softeer/orange/event/draw/component/score/actionHandler/WriteCommentActionHandlerTest.java
  src/test/java/hyundai/softeer/orange/event/draw/repository/CustomDrawEventWinningInfoRepositoryImplTest.java
  src/test/java/hyundai/softeer/orange/event/draw/repository/EventParticipationInfoRepositoryTest.java
  src/test/java/hyundai/softeer/orange/event/draw/service/DrawEventServiceTest.java
  src/test/resources/sql/CommentRepositoryTest.sql
  src/test/resources/sql/CustomDrawEventWinningInfoRepositoryImplTest.sql
  src/test/resources/sql/EventParticipationInfoRepositoryTest.sql
Labels: feat

#45 [chore] 선착순 이벤트 부하 테스트 관련 일부 수정 (#44)
  src/main/java/hyundai/softeer/orange/event/fcfs/service/DbFcfsService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsAnswerService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsManageService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisLockFcfsService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisLuaFcfsService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisSetFcfsService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/util/FcfsUtil.java
Labels: fix, chore

#50 [fix] API Spec 수정 (#47)
  src/main/java/hyundai/softeer/orange/comment/controller/CommentController.java
  src/main/java/hyundai/softeer/orange/comment/dto/CreateCommentDto.java
  src/main/java/hyundai/softeer/orange/comment/repository/CommentRepository.java
  src/main/java/hyundai/softeer/orange/comment/scheduler/CommentScheduler.java
  src/main/java/hyundai/softeer/orange/comment/service/CommentService.java
  src/main/java/hyundai/softeer/orange/event/common/repository/EventFrameRepository.java
  src/main/java/hyundai/softeer/orange/event/fcfs/controller/FcfsController.java
  src/main/java/hyundai/softeer/orange/event/fcfs/dto/RequestAnswerDto.java
  src/test/java/hyundai/softeer/orange/comment/CommentControllerTest.java
  src/test/java/hyundai/softeer/orange/comment/CommentServiceTest.java
  src/test/java/hyundai/softeer/orange/event/fcfs/FcfsControllerTest.java
Labels: fix

#53 [chore] FE와 주고받는 EventFrame 식별자 PK가 아닌 별도 필드로 수정 (#52)
  src/main/java/hyundai/softeer/orange/admin/service/AdminAuthService.java
  src/main/java/hyundai/softeer/orange/comment/controller/CommentController.java
  src/main/java/hyundai/softeer/orange/comment/scheduler/CommentScheduler.java
  src/main/java/hyundai/softeer/orange/comment/service/ApiService.java
  src/main/java/hyundai/softeer/orange/comment/service/CommentService.java
  src/main/java/hyundai/softeer/orange/event/common/controller/AdminEventController.java
  src/main/java/hyundai/softeer/orange/event/common/entity/EventFrame.java
  src/main/java/hyundai/softeer/orange/event/common/repository/EventFrameRepository.java
  src/main/java/hyundai/softeer/orange/event/common/service/EventService.java
  src/main/java/hyundai/softeer/orange/event/draw/service/DrawEventService.java
  src/main/java/hyundai/softeer/orange/event/dto/EventFrameCreateRequest.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsManageService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisLuaFcfsService.java
  src/main/java/hyundai/softeer/orange/event/url/service/UrlService.java
  src/main/java/hyundai/softeer/orange/eventuser/controller/EventUserController.java
  src/main/java/hyundai/softeer/orange/eventuser/service/CoolSmsService.java
  src/main/java/hyundai/softeer/orange/eventuser/service/EventUserService.java
  src/test/java/hyundai/softeer/orange/comment/CommentControllerTest.java
  src/test/java/hyundai/softeer/orange/comment/CommentServiceTest.java
  src/test/java/hyundai/softeer/orange/event/common/repository/EventSpecificationTest.java
  src/test/java/hyundai/softeer/orange/event/common/service/EventServiceSearchEventsTest.java
  src/test/java/hyundai/softeer/orange/event/common/service/EventServiceSearchHintsTest.java
  src/test/java/hyundai/softeer/orange/event/common/service/EventServiceTest.java
  src/test/java/hyundai/softeer/orange/event/fcfs/FcfsManageServiceTest.java
  src/test/java/hyundai/softeer/orange/eventuser/EventUserControllerTest.java
  src/test/java/hyundai/softeer/orange/eventuser/EventUserServiceTest.java
  src/test/resources/sql/CommentRepositoryTest.sql
  src/test/resources/sql/CustomDrawEventWinningInfoRepositoryImplTest.sql
  src/test/resources/sql/EventParticipationInfoRepositoryTest.sql
Labels: fix

#55 [feat] 추첨 이벤트 참여 관련 api 구현(#51)
  src/main/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/DrawEventFieldMapper.java
  src/main/java/hyundai/softeer/orange/event/common/entity/EventMetadata.java
  src/main/java/hyundai/softeer/orange/event/draw/controller/DrawEventController.java
  src/main/java/hyundai/softeer/orange/event/draw/dto/EventParticipationDateDto.java
  src/main/java/hyundai/softeer/orange/event/draw/dto/EventParticipationDatesDto.java
  src/main/java/hyundai/softeer/orange/event/draw/entity/DrawEvent.java
  src/main/java/hyundai/softeer/orange/event/draw/entity/EventParticipationInfo.java
  src/main/java/hyundai/softeer/orange/event/draw/repository/EventParticipationInfoRepository.java
  src/main/java/hyundai/softeer/orange/event/draw/service/EventParticipationService.java
  src/test/java/hyundai/softeer/orange/comment/repository/CommentRepositoryTest.java
  src/test/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/DrawEventFieldMapperTest.java
  src/test/java/hyundai/softeer/orange/event/draw/repository/CustomDrawEventWinningInfoRepositoryImplTest.java
  src/test/java/hyundai/softeer/orange/event/draw/repository/EventParticipationInfoRepositoryTest.java
  src/test/java/hyundai/softeer/orange/event/draw/service/EventParticipationServiceTest.java
  src/test/resources/sql/EventParticipationInfoRepositoryTest.sql
  src/test/resources/sql/RefreshTable.sql
Labels: feat

#59 [chore] swagger jwt 인증기능 추가(#56)
  src/main/java/hyundai/softeer/orange/admin/controller/AdminAuthController.java
  src/main/java/hyundai/softeer/orange/admin/controller/AdminCommentController.java
  src/main/java/hyundai/softeer/orange/config/SwaggerConfig.java
  src/main/java/hyundai/softeer/orange/core/auth/AuthConst.java
  src/main/java/hyundai/softeer/orange/core/auth/list/AdminAuthRequirement.java
  src/main/java/hyundai/softeer/orange/core/auth/list/EventUserAuthRequirement.java
  src/main/java/hyundai/softeer/orange/event/common/controller/AdminEventController.java
Labels: chore

#61 [fix] RedisConfig 직렬화 관련 hotfix (#60)
  src/main/java/hyundai/softeer/orange/config/RedisConfig.java
Labels: fix

#65 [chore] api 변경 사항에 맞게 이벤트 dto 규격 수정(#63)
  src/main/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/FcfsEventFieldMapper.java
  src/main/java/hyundai/softeer/orange/event/common/service/EventService.java
  src/main/java/hyundai/softeer/orange/event/dto/EventDto.java
  src/main/java/hyundai/softeer/orange/event/dto/draw/DrawEventDto.java
  src/main/java/hyundai/softeer/orange/event/dto/draw/DrawEventMetadataDto.java
  src/main/java/hyundai/softeer/orange/event/dto/draw/DrawEventScorePolicyDto.java
  src/main/java/hyundai/softeer/orange/event/dto/fcfs/FcfsEventDto.java
  src/test/java/hyundai/softeer/orange/event/common/service/EventServiceTest.java
Labels: chore

#66 [feat] 관리자 이벤트 검색 기능에 필터링 기능 추가(#62)
  src/main/java/hyundai/softeer/orange/admin/controller/AdminEventController.java
  src/main/java/hyundai/softeer/orange/common/ErrorCode.java
  src/main/java/hyundai/softeer/orange/event/common/EventConst.java
  src/main/java/hyundai/softeer/orange/event/common/repository/EventSpecification.java
  src/main/java/hyundai/softeer/orange/event/common/service/EventService.java
  src/main/java/hyundai/softeer/orange/event/dto/BriefEventPageDto.java
  src/test/java/hyundai/softeer/orange/event/common/service/EventServiceSearchEventsTest.java
  src/test/java/hyundai/softeer/orange/event/common/service/EventServiceTest.java
  src/test/resources/sql/RefreshTable.sql
Labels: feat

#68 [test] 테스트 컨테이너 조성 및 CI 파이프라인과 연계 (#64)
  .github/workflows/CI.yml
  build.gradle
  src/main/java/hyundai/softeer/orange/common/util/ConstantUtil.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsManageService.java
  src/main/resources/application-test.yml
  src/main/resources/logback-spring.xml
  src/test/java/hyundai/softeer/orange/OrangeApplicationTests.java
  src/test/java/hyundai/softeer/orange/comment/repository/CommentRepositoryTest.java
  src/test/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/DrawEventFieldMapperTest.java
  src/test/java/hyundai/softeer/orange/event/common/repository/EventSpecificationTest.java
  src/test/java/hyundai/softeer/orange/event/common/service/EventServiceSearchEventsTest.java
  src/test/java/hyundai/softeer/orange/event/common/service/EventServiceSearchHintsTest.java
  src/test/java/hyundai/softeer/orange/event/common/service/EventServiceTest.java
  src/test/java/hyundai/softeer/orange/event/draw/repository/CustomDrawEventWinningInfoRepositoryImplTest.java
  src/test/java/hyundai/softeer/orange/event/draw/repository/EventParticipationInfoRepositoryTest.java
  src/test/java/hyundai/softeer/orange/event/fcfs/FcfsManageServiceTest.java
  src/test/java/hyundai/softeer/orange/load/DbFcfsServiceLoadTest.java
  src/test/java/hyundai/softeer/orange/load/RedisLockFcfsServiceLoadTest.java
  src/test/java/hyundai/softeer/orange/load/RedisLuaFcfsServiceLoadTest.java
  src/test/java/hyundai/softeer/orange/load/RedisSetFcfsServiceLoadTest.java
  src/test/java/hyundai/softeer/orange/support/TCDataJpaTest.java
  src/test/resources/sql/EventParticipationInfoRepositoryTest.sql
  src/test/resources/sql/RefreshTable.sql
Labels: infra, test

#70 [feat] 추첨 이벤트 재추첨 방지 로직 / api 구현(#67)
  src/main/java/hyundai/softeer/orange/OrangeApplication.java
  src/main/java/hyundai/softeer/orange/admin/controller/AdminDrawEventController.java
  src/main/java/hyundai/softeer/orange/common/ErrorCode.java
  src/main/java/hyundai/softeer/orange/event/common/EventConst.java
  src/main/java/hyundai/softeer/orange/event/common/service/EventService.java
  src/main/java/hyundai/softeer/orange/event/draw/entity/DrawEvent.java
  src/main/java/hyundai/softeer/orange/event/draw/repository/DrawEventRepository.java
  src/main/java/hyundai/softeer/orange/event/draw/service/DrawEventDrawMachine.java
  src/main/java/hyundai/softeer/orange/event/draw/service/DrawEventService.java
  src/test/java/hyundai/softeer/orange/event/draw/service/DrawEventDrawMachineTest.java
  src/test/java/hyundai/softeer/orange/event/draw/service/DrawEventServiceTest.java
  src/test/resources/sql/CustomDrawEventWinningInfoRepositoryImplTest.sql
  src/test/resources/sql/EventParticipationInfoRepositoryTest.sql
Labels: feat

#72 [test] 통합테스트 @DirtiesContext 제거하여 테스트 속도 개선 (#71)
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  src/test/java/hyundai/softeer/orange/comment/repository/CommentRepositoryTest.java
  src/test/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/DrawEventFieldMapperTest.java
  src/test/java/hyundai/softeer/orange/event/common/repository/EventSpecificationTest.java
  src/test/java/hyundai/softeer/orange/event/common/service/EventServiceSearchEventsTest.java
  src/test/java/hyundai/softeer/orange/event/common/service/EventServiceSearchHintsTest.java
  src/test/java/hyundai/softeer/orange/event/draw/repository/CustomDrawEventWinningInfoRepositoryImplTest.java
  src/test/java/hyundai/softeer/orange/event/draw/repository/EventParticipationInfoRepositoryTest.java
  src/test/java/hyundai/softeer/orange/support/IntegrationDataJpaTest.java
Labels: test

#76 [fix] CD 파이프라인 AWS Role 기반으로 수정 (#74)
  .github/workflows/CD.yml
  src/main/resources/logback-spring.xml
Labels: fix, infra

#78 [feat] 기대평 작성 기능 누락된 요구사항 반영 (#77)
  src/main/java/hyundai/softeer/orange/comment/service/CommentService.java
  src/main/java/hyundai/softeer/orange/common/ErrorCode.java
  src/main/java/hyundai/softeer/orange/event/draw/repository/DrawEventRepository.java
  src/test/java/hyundai/softeer/orange/comment/CommentServiceTest.java
Labels: feat

#79 [feat] 관리자 댓글 검색 기능 추가(#73)
  src/main/java/hyundai/softeer/orange/admin/controller/AdminCommentController.java
  src/main/java/hyundai/softeer/orange/comment/repository/CommentRepository.java
  src/main/java/hyundai/softeer/orange/comment/repository/CommentSpecification.java
  src/main/java/hyundai/softeer/orange/comment/service/CommentService.java
  src/main/java/hyundai/softeer/orange/event/common/entity/EventMetadata.java
  src/main/java/hyundai/softeer/orange/event/draw/entity/DrawEvent.java
  src/main/java/hyundai/softeer/orange/event/draw/service/DrawEventService.java
  src/test/java/hyundai/softeer/orange/comment/CommentServiceTest.java
  src/test/java/hyundai/softeer/orange/event/draw/service/DrawEventServiceTest.java
  src/test/java/hyundai/softeer/orange/event/draw/service/EventParticipationServiceTest.java
Labels: feat

#81 [feat] 당첨자 목록 조회 기능 구현 (#80)
  src/main/java/hyundai/softeer/orange/admin/controller/AdminDrawEventController.java
  src/main/java/hyundai/softeer/orange/comment/repository/CommentRepository.java
  src/main/java/hyundai/softeer/orange/event/draw/dto/ResponseDrawWinnerDto.java
  src/main/java/hyundai/softeer/orange/event/draw/entity/DrawEventWinningInfo.java
  src/main/java/hyundai/softeer/orange/event/draw/repository/DrawEventWinningInfoRepository.java
  src/main/java/hyundai/softeer/orange/event/draw/service/DrawEventService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/dto/ResponseFcfsWinnerDto.java
  src/main/java/hyundai/softeer/orange/event/fcfs/entity/FcfsEventWinningInfo.java
  src/main/java/hyundai/softeer/orange/event/fcfs/repository/FcfsEventWinningInfoRepository.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/DbFcfsService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsManageService.java
  src/test/java/hyundai/softeer/orange/event/draw/service/DrawEventServiceTest.java
  src/test/java/hyundai/softeer/orange/event/fcfs/FcfsManageServiceTest.java
Labels: feat

#87 [chore] swagger에 이벤트 유저 인증 api 명시(#86)
  src/main/java/hyundai/softeer/orange/admin/controller/AdminDrawEventController.java
  src/main/java/hyundai/softeer/orange/comment/controller/CommentController.java
  src/main/java/hyundai/softeer/orange/event/draw/controller/DrawEventController.java
  src/main/java/hyundai/softeer/orange/event/draw/service/DrawEventDrawMachine.java
  src/main/java/hyundai/softeer/orange/event/fcfs/controller/FcfsController.java
Labels: chore

#85 [infra] Grafana 기반 서버 상태 및 로그 모니터링 시스템 구축 (#82)
  .github/workflows/CD.yml
  build.gradle
  infra/docker-compose.yml
  infra/promtail-config.yml
Labels: infra

#90 [feat] 추첨 이벤트 현재 상태 API 구현(#88)
  src/main/java/hyundai/softeer/orange/admin/controller/AdminDrawEventController.java
  src/main/java/hyundai/softeer/orange/event/common/entity/EventMetadata.java
  src/main/java/hyundai/softeer/orange/event/draw/dto/DrawEventStatusDto.java
  src/main/java/hyundai/softeer/orange/event/draw/enums/DrawEventStatus.java
  src/main/java/hyundai/softeer/orange/event/draw/service/DrawEventService.java
  src/test/java/hyundai/softeer/orange/event/draw/service/DrawEventServiceTest.java
Labels: feat

#91 [fix] Prod 환경 기준 API 검증 및 버그 수정 (#89)
  src/main/java/hyundai/softeer/orange/comment/controller/CommentController.java
  src/main/java/hyundai/softeer/orange/comment/dto/DeleteCommentsDto.java
  src/main/java/hyundai/softeer/orange/comment/service/CommentService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/scheduler/FcfsScheduler.java
Labels: fix

#95 [refactor] 어드민 토큰에 최소한의 내용만 포함되도록 수정(#92)
  src/main/java/hyundai/softeer/orange/admin/component/AdminArgumentResolver.java
  src/main/java/hyundai/softeer/orange/admin/controller/AdminAuthController.java
  src/main/java/hyundai/softeer/orange/admin/controller/AdminEventController.java
  src/main/java/hyundai/softeer/orange/admin/dto/AdminDto.java
  src/main/java/hyundai/softeer/orange/admin/service/AdminAuthService.java
  src/main/java/hyundai/softeer/orange/common/util/ConstantUtil.java
  src/main/java/hyundai/softeer/orange/eventuser/component/EventUserArgumentResolver.java
  src/main/java/hyundai/softeer/orange/eventuser/service/EventUserService.java
Labels: fix, refactor

#96 [fix] 선착순 이벤트 상태 조회 기능 응답값 수정 (#94)
  src/main/java/hyundai/softeer/orange/event/fcfs/dto/ResponseFcfsInfoDto.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsManageService.java
Labels: fix

#97 [refactor] 어드민 댓글 api가 페이지 관련 정보를 함께 반환하도록 수정(#93)
  src/main/java/hyundai/softeer/orange/admin/controller/AdminCommentController.java
  src/main/java/hyundai/softeer/orange/comment/dto/CommentsPageDto.java
  src/main/java/hyundai/softeer/orange/comment/service/CommentService.java
  src/test/java/hyundai/softeer/orange/comment/CommentServiceTest.java
Labels: feat

#100 [fix] docker-compose 컨테이너 시각 UTC로 설정된 버그 수정 (#99)
  infra/docker-compose.yml
Labels: fix, infra

#102 [refactor] 관리자 이벤트 생성 시 이벤트 프레임도 함께 생성할 수 있도록 변경, 이벤트 프레임 검색 api 구현(#98)
  src/main/java/hyundai/softeer/orange/admin/controller/AdminEventController.java
  src/main/java/hyundai/softeer/orange/admin/controller/EventFrameIdListDto.java
  src/main/java/hyundai/softeer/orange/event/common/repository/EventFrameRepository.java
  src/main/java/hyundai/softeer/orange/event/common/service/EventService.java
  src/test/java/hyundai/softeer/orange/event/common/service/EventServiceTest.java
Labels: refactor, feat

#105 [refactor] 선착순 이벤트 API 매개변수 eventSequenced에서 eventId로 변경 (#101)
  src/main/java/hyundai/softeer/orange/comment/scheduler/CommentScheduler.java
  src/main/java/hyundai/softeer/orange/common/util/ConstantUtil.java
  src/main/java/hyundai/softeer/orange/event/fcfs/controller/FcfsController.java
  src/main/java/hyundai/softeer/orange/event/fcfs/scheduler/FcfsScheduler.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/DbFcfsService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsAnswerService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsManageService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisLockFcfsService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisLuaFcfsService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisSetFcfsService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/util/FcfsUtil.java
  src/test/java/hyundai/softeer/orange/event/fcfs/FcfsControllerTest.java
  src/test/java/hyundai/softeer/orange/event/fcfs/FcfsManageServiceTest.java
  src/test/java/hyundai/softeer/orange/load/DbFcfsServiceLoadTest.java
  src/test/java/hyundai/softeer/orange/load/RedisLockFcfsServiceLoadTest.java
  src/test/java/hyundai/softeer/orange/load/RedisLuaFcfsServiceLoadTest.java
  src/test/java/hyundai/softeer/orange/load/RedisSetFcfsServiceLoadTest.java
Labels: refactor

#104 [feat] 선착순 이벤트 생성 및 수정 시 시간대 검증 기능 추가(#103)
  .gitignore
  src/main/java/hyundai/softeer/orange/common/ErrorCode.java
  src/main/java/hyundai/softeer/orange/common/GlobalExceptionHandler.java
  src/main/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/FcfsEventFieldMapper.java
  src/main/java/hyundai/softeer/orange/event/dto/EventDto.java
  src/main/java/hyundai/softeer/orange/event/dto/fcfs/FcfsEventDto.java
  src/main/java/hyundai/softeer/orange/event/dto/validator/EventDtoTimeValidation.java
  src/main/java/hyundai/softeer/orange/event/dto/validator/EventDtoTimeValidator.java
  src/main/java/hyundai/softeer/orange/event/dto/validator/FcfsEventDtoTimeValidation.java
  src/main/java/hyundai/softeer/orange/event/dto/validator/FcfsEventDtoTimeValidator.java
  src/main/resources/errors.properties
  src/main/resources/errors_ko_KR.properties
  src/main/resources/logback-spring.xml
  src/test/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/FcfsEventFieldMapperTest.java
Labels: feat

#108 [feat] 추첨 이벤트 생성 및 수정 시 검증 기능 추가(#106)
  src/main/java/hyundai/softeer/orange/common/ErrorCode.java
  src/main/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/DrawEventFieldMapper.java
  src/main/java/hyundai/softeer/orange/event/dto/draw/DrawEventMetadataDto.java
  src/main/java/hyundai/softeer/orange/event/dto/draw/DrawEventScorePolicyDto.java
  src/main/java/hyundai/softeer/orange/event/dto/fcfs/FcfsEventDto.java
  src/test/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/DrawEventFieldMapperTest.java
Labels: feat

#109 [fix] 추첨 이벤트 참여 대상이 아닌 이벤트 유저가 참여할 수 있는 문제 수정(#107)
  src/main/java/hyundai/softeer/orange/core/auth/AuthInterceptor.java
  src/main/java/hyundai/softeer/orange/event/common/entity/EventMetadata.java
  src/main/java/hyundai/softeer/orange/event/draw/service/EventParticipationService.java
  src/main/java/hyundai/softeer/orange/eventuser/entity/EventUser.java
  src/test/java/hyundai/softeer/orange/event/draw/service/EventParticipationServiceTest.java
Labels: fix

#111 [refactor, feat] 이벤트 정보가 프레임을 포함하여 반환하도록 수정 외(#110)
  src/main/java/hyundai/softeer/orange/admin/controller/AdminEventUserController.java
  src/main/java/hyundai/softeer/orange/event/common/repository/EventMetadataRepository.java
  src/main/java/hyundai/softeer/orange/event/common/service/EventService.java
  src/main/java/hyundai/softeer/orange/eventuser/dto/EventUserOnAdminDto.java
  src/main/java/hyundai/softeer/orange/eventuser/dto/EventUserPageDto.java
  src/main/java/hyundai/softeer/orange/eventuser/repository/EventUserRepository.java
  src/main/java/hyundai/softeer/orange/eventuser/service/EventUserService.java
Labels: refactor, feat

#113 [refactor] Auth 어노테이션이 메타 어노테이션인 경우에도 대응할 수 있도록 변경(#112)
  src/main/java/hyundai/softeer/orange/admin/controller/AdminCommentController.java
  src/main/java/hyundai/softeer/orange/admin/controller/AdminDrawEventController.java
  src/main/java/hyundai/softeer/orange/admin/controller/AdminEventController.java
  src/main/java/hyundai/softeer/orange/admin/controller/AdminEventUserController.java
  src/main/java/hyundai/softeer/orange/comment/controller/CommentController.java
  src/main/java/hyundai/softeer/orange/core/auth/AuthInterceptor.java
  src/main/java/hyundai/softeer/orange/core/auth/list/AdminAuth.java
  src/main/java/hyundai/softeer/orange/core/auth/list/EventUserAuth.java
  src/main/java/hyundai/softeer/orange/event/draw/controller/DrawEventController.java
  src/main/java/hyundai/softeer/orange/event/fcfs/controller/FcfsController.java
Labels: refactor

#117 [chore] 키 규격을 HD_000000_000으로 변경(#116)
  src/main/java/hyundai/softeer/orange/event/component/EventKeyGenerator.java
  src/test/java/hyundai/softeer/orange/event/component/EventKeyGeneratorTest.java
Labels: chore

#120 [fix] 배포 환경에서 로그 수집이 멈추고 도커 이미지가 누적되는 버그 수정 (#118)
  .github/workflows/CD.yml
  infra/promtail-config.yml
  src/main/resources/logback-spring.xml
Labels: fix, infra

#121 [fix] 임시 이벤트를 정상적으로 저장 & 조회할 수 있도록 수정(#119)
  src/main/java/hyundai/softeer/orange/admin/component/AdminArgumentResolver.java
  src/main/java/hyundai/softeer/orange/admin/controller/AdminEventController.java
  src/main/java/hyundai/softeer/orange/config/RedisConfig.java
  src/main/java/hyundai/softeer/orange/core/JsonUtil.java
  src/main/java/hyundai/softeer/orange/core/ParseUtil.java
  src/main/java/hyundai/softeer/orange/event/common/service/EventService.java
Labels: fix

#123 [fix] 선착순 이벤트 정보 찾을 수 없던 버그 수정 (#122)
  src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsManageService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisLuaFcfsService.java
  src/test/java/hyundai/softeer/orange/event/fcfs/FcfsManageServiceTest.java
Labels: fix

#126 [chore] 선착순 이벤트 로깅 (#125)
  src/main/java/hyundai/softeer/orange/event/fcfs/controller/FcfsController.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisLuaFcfsService.java
Labels: chore

#128 [fix] LocalDateTime에 의한 타임존 문제 해결(#115)
  src/main/java/hyundai/softeer/orange/comment/dto/ResponseCommentDto.java
  src/main/java/hyundai/softeer/orange/comment/entity/Comment.java
  src/main/java/hyundai/softeer/orange/comment/service/CommentService.java
  src/main/java/hyundai/softeer/orange/common/util/DateUtil.java
  src/main/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/FcfsEventFieldMapper.java
  src/main/java/hyundai/softeer/orange/event/common/entity/EventMetadata.java
  src/main/java/hyundai/softeer/orange/event/component/EventKeyGenerator.java
  src/main/java/hyundai/softeer/orange/event/draw/dto/EventParticipationDateDto.java
  src/main/java/hyundai/softeer/orange/event/draw/dto/EventParticipationDatesDto.java
  src/main/java/hyundai/softeer/orange/event/draw/entity/EventParticipationInfo.java
  src/main/java/hyundai/softeer/orange/event/draw/repository/EventParticipationInfoRepository.java
  src/main/java/hyundai/softeer/orange/event/draw/service/DrawEventService.java
  src/main/java/hyundai/softeer/orange/event/draw/service/EventParticipationService.java
  src/main/java/hyundai/softeer/orange/event/dto/BriefEventDto.java
  src/main/java/hyundai/softeer/orange/event/dto/EventDto.java
  src/main/java/hyundai/softeer/orange/event/dto/fcfs/FcfsEventDto.java
  src/main/java/hyundai/softeer/orange/event/fcfs/dto/ResponseFcfsInfoDto.java
  src/main/java/hyundai/softeer/orange/event/fcfs/dto/ResponseFcfsWinnerDto.java
  src/main/java/hyundai/softeer/orange/event/fcfs/entity/FcfsEvent.java
  src/main/java/hyundai/softeer/orange/event/fcfs/entity/FcfsEventWinningInfo.java
  src/main/java/hyundai/softeer/orange/event/fcfs/repository/FcfsEventRepository.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/DbFcfsService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsAnswerService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsManageService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisLockFcfsService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisLuaFcfsService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisSetFcfsService.java
  src/test/java/hyundai/softeer/orange/comment/CommentServiceTest.java
  src/test/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/FcfsEventFieldMapperTest.java
  src/test/java/hyundai/softeer/orange/event/common/service/EventServiceSearchEventsTest.java
  src/test/java/hyundai/softeer/orange/event/common/service/EventServiceSearchHintsTest.java
  src/test/java/hyundai/softeer/orange/event/draw/service/DrawEventServiceTest.java
  src/test/java/hyundai/softeer/orange/event/draw/service/EventParticipationServiceTest.java
  src/test/java/hyundai/softeer/orange/event/fcfs/FcfsControllerTest.java
  src/test/java/hyundai/softeer/orange/event/fcfs/FcfsManageServiceTest.java
  src/test/java/hyundai/softeer/orange/load/DbFcfsServiceLoadTest.java
Labels: fix, refactor

#130 [fix] 이벤트 수정 시 fcfs / draw에서 2개 이상의 객체 추가 시 예외 발생하는 현상 수정(#124)
  src/main/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/DrawEventFieldMapper.java
  src/main/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/FcfsEventFieldMapper.java
  src/main/java/hyundai/softeer/orange/event/dto/group/EventEditGroup.java
  src/test/resources/sql/RefreshTable.sql
Labels: fix

#132 [chore] Redis Key Name 난잡한 상황 개선 (#129)
  src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsManageService.java
  src/main/java/hyundai/softeer/orange/event/fcfs/util/FcfsUtil.java
  src/test/java/hyundai/softeer/orange/event/fcfs/FcfsManageServiceTest.java
Labels: chore

#134 [feat] 이벤트 삭제 기능 구현(#131)
  src/main/java/hyundai/softeer/orange/admin/controller/AdminEventController.java
  src/main/java/hyundai/softeer/orange/common/ErrorCode.java
  src/main/java/hyundai/softeer/orange/event/common/entity/EventMetadata.java
  src/main/java/hyundai/softeer/orange/event/common/service/EventService.java
  src/main/java/hyundai/softeer/orange/event/draw/entity/DrawEvent.java
  src/test/java/hyundai/softeer/orange/event/common/service/EventServiceTest.java
Labels: feat

#138 [fix] 선착순 이벤트 가져오기 조건 잘못되어 있던 버그 수정 (#137)
  src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsManageService.java
Labels: fix

#139 [feat] 이벤트 유저를 다양한 조건으로 검색할 수 있게 개선(#135)
  build.gradle
  src/main/java/hyundai/softeer/orange/admin/controller/AdminEventUserController.java
  src/main/java/hyundai/softeer/orange/config/QueryDSLConfig.java
  src/main/java/hyundai/softeer/orange/eventuser/repository/CustomEventUserRepository.java
  src/main/java/hyundai/softeer/orange/eventuser/repository/CustomEventUserRepositoryImpl.java
  src/main/java/hyundai/softeer/orange/eventuser/repository/EventUserRepository.java
  src/main/java/hyundai/softeer/orange/eventuser/service/EventUserService.java
  src/test/java/hyundai/softeer/orange/support/TCDataJpaTest.java
  src/test/java/hyundai/softeer/orange/support/TestConfig.java
Labels: feat

#142 [fix] 이벤트 식별자가 누락되어 로그인 필터링 과정에서 발생하던 에러 수정 (#140)
  src/main/java/hyundai/softeer/orange/event/fcfs/controller/FcfsController.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisLuaFcfsService.java
  src/main/java/hyundai/softeer/orange/eventuser/controller/EventUserController.java
  src/main/java/hyundai/softeer/orange/eventuser/repository/EventUserRepository.java
  src/main/java/hyundai/softeer/orange/eventuser/service/EventUserService.java
  src/test/java/hyundai/softeer/orange/eventuser/EventUserControllerTest.java
  src/test/java/hyundai/softeer/orange/eventuser/EventUserServiceTest.java
Labels: fix

#144 [fix] 스케줄러 의도대로 동작하지 않는 버그 수정 (#143)
  src/main/java/hyundai/softeer/orange/event/fcfs/scheduler/FcfsScheduler.java
  src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsManageService.java
Labels: fix

#146 [fix] 추첨 이벤트 결과 당첨자 1명만 조회되던 버그 수정 (#145)
  src/main/java/hyundai/softeer/orange/event/draw/repository/DrawEventWinningInfoRepository.java
  src/main/java/hyundai/softeer/orange/event/draw/service/DrawEventService.java
  src/test/java/hyundai/softeer/orange/event/draw/service/DrawEventServiceTest.java
Labels: fix

#148 [fix] 이벤트 유저 검색에 페이징 동작하지 않는 현상 수정(#147)
  src/main/java/hyundai/softeer/orange/admin/controller/AdminEventController.java
  src/main/java/hyundai/softeer/orange/event/common/repository/EventMetadataRepository.java
  src/main/java/hyundai/softeer/orange/event/common/service/EventService.java
  src/main/java/hyundai/softeer/orange/event/draw/service/DrawEventDrawMachine.java
  src/main/java/hyundai/softeer/orange/event/dto/DeleteEventNotAllowedReasonDto.java
  src/main/java/hyundai/softeer/orange/event/dto/DeleteEventsDto.java
  src/main/java/hyundai/softeer/orange/eventuser/repository/CustomEventUserRepositoryImpl.java
Labels: fix, feat

#149 [fix] deleteAllInBatch로 인해 이벤트의 연관관계를 삭제하지 못해 외래키 에러가 발생하던 문제 수정 (#147)
  src/main/java/hyundai/softeer/orange/common/ErrorCode.java
  src/main/java/hyundai/softeer/orange/event/common/service/EventService.java
  src/main/java/hyundai/softeer/orange/event/draw/service/DrawEventDrawMachine.java
Labels: feat

#151 [fix] 기대평 필터링 기준 재조정 (#150)
  src/main/java/hyundai/softeer/orange/common/ErrorCode.java
  src/main/java/hyundai/softeer/orange/common/util/ConstantUtil.java
Labels: fix

#152 [chore] delete many 시 조건을 null 체크로 처리해 항상 예외로 간주하는 문제 수정 (#147)
  src/main/java/hyundai/softeer/orange/admin/controller/AdminEventController.java
Labels: fix

#154 [fix] 이벤트 유저 수가 0명일 때 set 기반 추첨을 진행하면 예외가 발생하는 문제 수정(#153)
  src/main/java/hyundai/softeer/orange/event/draw/component/picker/AccSumBasedWinnerPicker.java
  src/main/java/hyundai/softeer/orange/event/draw/service/DrawEventDrawMachine.java
Labels: fix

#156 [chore] 불필요한 import 제거 등 코드 정리 (#155)
  src/main/java/hyundai/softeer/orange/admin/controller/AdminAuthController.java
  src/main/java/hyundai/softeer/orange/common/GlobalExceptionHandler.java
  src/main/java/hyundai/softeer/orange/config/WebConfig.java
  src/main/java/hyundai/softeer/orange/event/component/EventKeyGenerator.java
  src/main/java/hyundai/softeer/orange/event/draw/entity/DrawEvent.java
  src/main/java/hyundai/softeer/orange/event/dto/EventSearchHintDto.java
  src/main/java/hyundai/softeer/orange/event/dto/draw/DrawEventDto.java
  src/main/java/hyundai/softeer/orange/event/dto/draw/DrawEventScorePolicyDto.java
  src/main/java/hyundai/softeer/orange/eventuser/repository/CustomEventUserRepository.java
  src/test/java/hyundai/softeer/orange/core/jwt/JWTManagerTest.java
  src/test/java/hyundai/softeer/orange/core/jwt/JwtTest.java
  src/test/java/hyundai/softeer/orange/core/security/PasswordManagerDefaultImplTest.java
  src/test/java/hyundai/softeer/orange/core/security/RandomStrGeneratorTest.java
  src/test/java/hyundai/softeer/orange/event/common/component/query/EventSearchQueryParserTest.java
  src/test/java/hyundai/softeer/orange/event/component/EventKeyGeneratorTest.java
  src/test/java/hyundai/softeer/orange/event/draw/component/picker/AccSumBasedWinnerPickerTest.java
  src/test/java/hyundai/softeer/orange/event/draw/component/score/ScoreCalculatorTest.java
  src/test/java/hyundai/softeer/orange/event/fcfs/FcfsControllerTest.java
  src/test/java/hyundai/softeer/orange/support/IntegrationDataJpaTest.java
Labels: chore
