Repository softeerbootcamp4th/Team6-AwesomeOrange-BE, pull requests merged in 2024-07, with the labels that each got.

#2 [docs] README 업데이트 (#1)
  README.md
Labels: docs

#3 [docs] README 기술스택 아이콘화 (#1)
  README.md
Labels: docs

#5 [infra] VPC, Subnet 설정 및 Github Actions 기반 CI/CD 파이프라인 구축 (#4)
  .github/workflows/gradle.yml
  .gitignore
  Dockerfile
  build.gradle
Labels: infra

#6 [fix] merge되었을 때만 CD가 동작하도록 CI/CD 파일 수정 (#4)
  .github/workflows/gradle.yml
Labels: infra

#9 [feat] 엔티티 및 레포지토리 생성 (#8)
  src/main/java/hyundai/softeer/orange/OrangeApplication.java
  src/main/java/hyundai/softeer/orange/admin/entity/Admin.java
  src/main/java/hyundai/softeer/orange/admin/repository/AdminRepository.java
  src/main/java/hyundai/softeer/orange/comment/entity/Comment.java
  src/main/java/hyundai/softeer/orange/comment/repository/CommentRepository.java
  src/main/java/hyundai/softeer/orange/event/common/entity/EventFrame.java
  src/main/java/hyundai/softeer/orange/event/common/entity/EventMetadata.java
  src/main/java/hyundai/softeer/orange/event/common/enums/EventStatus.java
  src/main/java/hyundai/softeer/orange/event/common/enums/EventType.java
  src/main/java/hyundai/softeer/orange/event/common/repository/EventFrameRepository.java
  src/main/java/hyundai/softeer/orange/event/common/repository/EventMetadataRepository.java
  src/main/java/hyundai/softeer/orange/event/draw/entity/DrawEvent.java
  src/main/java/hyundai/softeer/orange/event/draw/entity/DrawEventMetadata.java
  src/main/java/hyundai/softeer/orange/event/draw/entity/DrawEventScorePolicy.java
  src/main/java/hyundai/softeer/orange/event/draw/entity/DrawEventWinningInfo.java
  src/main/java/hyundai/softeer/orange/event/draw/entity/EventParticipationInfo.java
  src/main/java/hyundai/softeer/orange/event/draw/enums/DrawEventAction.java
  src/main/java/hyundai/softeer/orange/event/draw/repository/DrawEventMetadataRepository.java
  src/main/java/hyundai/softeer/orange/event/draw/repository/DrawEventRepository.java
  src/main/java/hyundai/softeer/orange/event/draw/repository/DrawEventScorePolicyRepository.java
  src/main/java/hyundai/softeer/orange/event/draw/repository/DrawEventWinningInfoRepository.java
  src/main/java/hyundai/softeer/orange/event/draw/repository/EventParticipationInfoRepository.java
  src/main/java/hyundai/softeer/orange/event/fcfs/entity/FcfsEvent.java
  src/main/java/hyundai/softeer/orange/event/fcfs/entity/FcfsEventWinningInfo.java
  src/main/java/hyundai/softeer/orange/event/fcfs/repository/FcfsEventRepository.java
  src/main/java/hyundai/softeer/orange/event/fcfs/repository/FcfsEventWinningInfoRepository.java
  src/main/java/hyundai/softeer/orange/eventuser/entity/EventUser.java
  src/main/java/hyundai/softeer/orange/eventuser/repository/EventUserRepository.java
  src/main/resources/application.properties
Labels: feat

#10 [fix] entity 필드 이름 문제 및 관계 누락 문제 수정(#8)
  src/main/java/hyundai/softeer/orange/event/draw/entity/DrawEventWinningInfo.java
  src/main/java/hyundai/softeer/orange/event/fcfs/entity/FcfsEventWinningInfo.java
  src/main/java/hyundai/softeer/orange/eventuser/entity/EventUser.java
Labels: fix

#11 [infra] CI와 CD 별도 파일로 분리 (#4)
  .github/workflows/CD.yml
  .github/workflows/CI.yml
Labels: fix

#15 [feat] 기대평 작성 기능 구현 (#12)
  .github/workflows/CD.yml
  build.gradle
  src/main/java/hyundai/softeer/orange/OrangeApplication.java
  src/main/java/hyundai/softeer/orange/comment/controller/CommentController.java
  src/main/java/hyundai/softeer/orange/comment/dto/CreateCommentDto.java
  src/main/java/hyundai/softeer/orange/comment/dto/ResponseCommentDto.java
  src/main/java/hyundai/softeer/orange/comment/dto/ResponseCommentsDto.java
  src/main/java/hyundai/softeer/orange/comment/entity/Comment.java
  src/main/java/hyundai/softeer/orange/comment/exception/CommentException.java
  src/main/java/hyundai/softeer/orange/comment/repository/CommentRepository.java
  src/main/java/hyundai/softeer/orange/comment/scheduler/CommentScheduler.java
  src/main/java/hyundai/softeer/orange/comment/service/ApiService.java
  src/main/java/hyundai/softeer/orange/comment/service/CommentService.java
  src/main/java/hyundai/softeer/orange/common/BaseException.java
  src/main/java/hyundai/softeer/orange/common/ErrorCode.java
  src/main/java/hyundai/softeer/orange/common/ErrorResponse.java
  src/main/java/hyundai/softeer/orange/common/GlobalExceptionHandler.java
  src/main/java/hyundai/softeer/orange/common/util/ConstantUtil.java
  src/main/java/hyundai/softeer/orange/common/util/MessageUtil.java
  src/main/java/hyundai/softeer/orange/config/NaverApiConfig.java
  src/main/java/hyundai/softeer/orange/config/RedisConfig.java
  src/main/java/hyundai/softeer/orange/config/SwaggerConfig.java
  src/main/java/hyundai/softeer/orange/event/common/entity/EventFrame.java
  src/main/java/hyundai/softeer/orange/eventuser/entity/EventUser.java
  src/test/java/hyundai/softeer/orange/comment/CommentControllerTest.java
  src/test/java/hyundai/softeer/orange/comment/CommentServiceTest.java
Labels: feat

#18 [feat] 관리자 로그인 기능 구현(#16)
  build.gradle
  src/main/java/hyundai/softeer/orange/admin/component/AdminAnnotation.java
  src/main/java/hyundai/softeer/orange/admin/component/AdminArgumentResolver.java
  src/main/java/hyundai/softeer/orange/admin/controller/AdminController.java
  src/main/java/hyundai/softeer/orange/admin/dto/AdminSignInRequest.java
  src/main/java/hyundai/softeer/orange/admin/dto/AdminSignupRequest.java
  src/main/java/hyundai/softeer/orange/admin/entity/Admin.java
  src/main/java/hyundai/softeer/orange/admin/repository/AdminRepository.java
  src/main/java/hyundai/softeer/orange/admin/service/AdminAuthService.java
  src/main/java/hyundai/softeer/orange/common/dto/TokenDto.java
  src/main/java/hyundai/softeer/orange/core/WebConfig.java
  src/main/java/hyundai/softeer/orange/core/auth/Auth.java
  src/main/java/hyundai/softeer/orange/core/auth/AuthInterceptor.java
  src/main/java/hyundai/softeer/orange/core/auth/AuthNameUtil.java
  src/main/java/hyundai/softeer/orange/core/jwt/JWTManager.java
  src/main/java/hyundai/softeer/orange/core/security/PasswordManager.java
  src/main/java/hyundai/softeer/orange/core/security/PasswordManagerDefaultImpl.java
  src/main/java/hyundai/softeer/orange/core/security/RandomStrGenerator.java
  src/test/java/hyundai/softeer/orange/core/auth/AuthNameUtilTest.java
  src/test/java/hyundai/softeer/orange/core/jwt/JWTManagerTest.java
  src/test/java/hyundai/softeer/orange/core/jwt/JwtTest.java
  src/test/java/hyundai/softeer/orange/core/security/PasswordManagerDefaultImplTest.java
  src/test/java/hyundai/softeer/orange/core/security/RandomStrGeneratorTest.java
Labels: feat

#20 [refactor] 프로젝트에 맞게 admin 예외처리, 폴더 구조 리팩토링(#19)
  src/main/java/hyundai/softeer/orange/admin/component/AdminArgumentResolver.java
  src/main/java/hyundai/softeer/orange/admin/controller/AdminController.java
  src/main/java/hyundai/softeer/orange/admin/exception/AdminException.java
  src/main/java/hyundai/softeer/orange/admin/service/AdminAuthService.java
  src/main/java/hyundai/softeer/orange/common/ErrorCode.java
  src/main/java/hyundai/softeer/orange/common/GlobalExceptionHandler.java
  src/main/java/hyundai/softeer/orange/common/exception/InternalServerException.java
  src/main/java/hyundai/softeer/orange/config/WebConfig.java
  src/main/java/hyundai/softeer/orange/core/security/PasswordManagerDefaultImpl.java
  src/test/java/hyundai/softeer/orange/core/auth/AuthNameUtilTest.java
  src/test/java/hyundai/softeer/orange/core/jwt/JWTManagerTest.java
  src/test/java/hyundai/softeer/orange/core/jwt/JwtTest.java
  src/test/java/hyundai/softeer/orange/core/security/PasswordManagerDefaultImplTest.java
  src/test/java/hyundai/softeer/orange/core/security/RandomStrGeneratorTest.java
Labels: refactor

#22 [feat] 이벤트유저 로그인 기능 구현 (#17)
  build.gradle
  src/main/java/hyundai/softeer/orange/comment/dto/ResponseCommentDto.java
  src/main/java/hyundai/softeer/orange/common/ErrorCode.java
  src/main/java/hyundai/softeer/orange/common/GlobalExceptionHandler.java
  src/main/java/hyundai/softeer/orange/common/util/ConstantUtil.java
  src/main/java/hyundai/softeer/orange/common/util/MessageUtil.java
  src/main/java/hyundai/softeer/orange/config/RedisConfig.java
  src/main/java/hyundai/softeer/orange/eventuser/config/CoolSmsApiConfig.java
  src/main/java/hyundai/softeer/orange/eventuser/controller/EventUserController.java
  src/main/java/hyundai/softeer/orange/eventuser/dto/RequestAuthCodeDto.java
  src/main/java/hyundai/softeer/orange/eventuser/dto/RequestUserDto.java
  src/main/java/hyundai/softeer/orange/eventuser/entity/EventUser.java
  src/main/java/hyundai/softeer/orange/eventuser/exception/EventUserException.java
  src/main/java/hyundai/softeer/orange/eventuser/repository/EventUserRepository.java
  src/main/java/hyundai/softeer/orange/eventuser/service/CoolSmsService.java
  src/main/java/hyundai/softeer/orange/eventuser/service/EventUserService.java
  src/main/java/hyundai/softeer/orange/eventuser/service/SmsService.java
  src/test/java/hyundai/softeer/orange/comment/CommentServiceTest.java
  src/test/java/hyundai/softeer/orange/eventuser/EventUserControllerTest.java
  src/test/java/hyundai/softeer/orange/eventuser/EventUserServiceTest.java
Labels: feat
